name: Package and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create addon package
      run: |
        # Create the addon directory structure
        mkdir -p Bezier

        # Copy addon files (exclude git and github files)
        cp *.toc *.lua Bezier/

        # Create the zip file
        zip -r Bezier.zip Bezier/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: Bezier.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
