name: Package and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create addon package
      run: |
        # Create the addon directory structure
        mkdir -p AchievementTracker

        # Copy addon files (exclude git and github files)
        cp *.toc *.lua AchievementTracker/

        # Create the zip file
        zip -r AchievementTracker.zip AchievementTracker/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: AchievementTracker.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
